name: OrnsteinUhlenbeckBridge
version: 1.0.0
author: Lawrence Murray
email: lawrence.murray@csiro.au
website-url: http://www.github.com/lawmurray/OrnsteinUhlenbeckBridge
download-url: http://www.github.com/lawmurray/OrnsteinUhlenbeckBridge/archive/master.tar.gz
github-url: http://www.github.com/lawmurray/OrnsteinUhlenbeckBridge
description: Ornstein--Uhlenbeck model for diffusion bridge sampling.
